=== MysteryCode/de.mysterycode.wcf.htaccess/htaccessContent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is used for xml-files which install, update or delete pages. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.woltlab.com" targetNamespace="http://www.woltlab.com" elementFormDefault="qualified">
	<!-- include types -->
	<xs:include schemaLocation="types.xsd" />
	
	<!-- data element -->
	<xs:element name="data">
		<xs:complexType>
			<xs:all>
				<xs:element name="import" type="import" minOccurs="0" />
				<xs:element name="delete" type="delete" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	
	<!-- import element -->
	<xs:complexType name="import">
		<xs:sequence>
			<xs:element name="content" type="content_import" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- delete element -->
	<xs:complexType name="delete">
		<xs:sequence>
			<xs:element name="content" type="content_delete" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- deleted menu item -->
	<xs:complexType name="content_delete">
		<xs:attribute name="identifier" type="woltlab_varchar" use="required" />
	</xs:complexType>
	
	<!-- imported/updated menu item -->
	<xs:complexType name="content_import">
		<xs:complexContent>
			<xs:extension base="content_delete">
				<xs:choice maxOccurs="unbounded">
					<xs:element name="module" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="content" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="parent" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="options" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="application" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="package" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="path" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="controller" type="woltlab_varchar" minOccurs="0" maxOccurs="1" />
					<xs:element name="global" type="woltlab_boolean" minOccurs="0" maxOccurs="1" />
					<xs:element name="unique" type="woltlab_boolean" minOccurs="0" maxOccurs="1" />
					<xs:element name="isSystem" type="woltlab_boolean" minOccurs="0" maxOccurs="1" />
					<xs:element name="isDynamic" type="woltlab_boolean" minOccurs="0" maxOccurs="1" />
					<xs:element name="force-file" type="woltlab_boolean" minOccurs="0" maxOccurs="1" />
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== MysteryCode/de.mysterycode.wcf.htaccess/htaccessContent.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns="http://www.woltlab.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.woltlab.com https://static.mysterycode.de/XSD/htaccessContent.xsd">
	<import>
		<content identifier="de.mysterycode.wcf.htaccess.ssl">
			<isDynamic>1</isDynamic> <!-- content is dynamic and will be provided by controller -->
			<options><![CDATA[]]></options> <!-- needed enabled/set options -->
			<module><![CDATA[mod_rewrite.c]]></module> <!-- needed apache module -->
			<controller><![CDATA[wcf\system\htaccess\snippet\SSLSnippetProvider]]></controller> <!-- controller/provider of the dynamic content -->
			<content><![CDATA[<IfModule mod_rewrite.c>
	RewriteEngine On
	RewriteCond %{HTTPS} off
	RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</IfModule>]]></content>

			<global>1</global> <!-- can be assigned to all applications -->
			<unique>1</unique> <!-- can be assigned onces per file only -->
			<path><![CDATA[]]></path>
		</content>

		<content identifier="de.mysterycode.wcf.htaccess.mcps">
			<isDynamic>1</isDynamic>
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<controller><![CDATA[wcf\system\htaccess\snippet\MCPSSnippetProvider]]></controller>
			<options>mcps_server,mcps_rewrite_enable</options>

			<force-file>1</force-file> <!-- can be assigned onces per file only -->

			<application>mcps</application>
			<path><![CDATA[]]></path>
			<package>de.mysterycode.mcps</package>
		</content>

		<content identifier="de.mysterycode.wcf.htaccess.seo">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Rewrite application „::APP_NAME::“ @ ::APP_DIR::
	RewriteCond %{SCRIPT_FILENAME} !-d
	RewriteCond %{SCRIPT_FILENAME} !-f
	RewriteRule ^::APP_DIR::(.*)$ ::APP_DIR::index.php?$1 [L,QSA]]]></content>

			<global>1</global>
			<path><![CDATA[]]></path>
		</content>

		<content identifier="de.mysterycode.wcf.htaccess.keepmaelstrom">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[# Rewrite application „::APP_NAME::“ (WCF 2.0) @ ::APP_DIR::
RewriteRule ^::APP_DIR::index.php/(.*) ::APP_DIR::index.php?$1 [L,QSA]]]></content>

			<global>1</global>
			<path><![CDATA[]]></path>
		</content>

		<content identifier="de.mysterycode.wcf.htaccess.keeptempest.wbb">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Rewrite application „::APP_NAME::“ (WCF 1.1) @ ::APP_DIR::
	RewriteCond %{QUERY_STRING} page=User&userID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?user/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=Thread&threadID=([0-9]+)&action=lastPost
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?thread/%1/&action=lastPost [R=301,L]
	RewriteCond %{QUERY_STRING} page=Thread&threadID=([0-9]+)&action=firstNew
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?thread/%1/&action=firstNew [R=301,L]
	RewriteCond %{QUERY_STRING} page=Thread&postID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?thread/thread/&postID=%1#post%1 [NE,R=301,L]
	RewriteCond %{QUERY_STRING} page=Thread&postID=([0-9]+)#post([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?thread/thread/&postID=%1#post%1 [NE,R=301,L]
	RewriteCond %{QUERY_STRING} page=Thread&threadID=([0-9]+)&pageNo=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?thread/%1/&pageNo=%2 [R=301,L]
	RewriteCond %{QUERY_STRING} page=Thread&threadID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?thread/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=Board&boardID=([0-9]+)&pageNo=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?board/%1/&pageNo=%2 [R=301,L]
	RewriteCond %{QUERY_STRING} page=Board&boardID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?board/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=Attachment&attachmentID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?attachment/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=Index
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?board-list/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=Portal
	RewriteRule ^::OLD_APP_DIR::index\.php$ index.php?dashboard/ [R=301,L]]]></content>

			<application>wbb</application>
			<package>com.woltlab.wbb</package>
			<path><![CDATA[]]></path>
		</content>
		<content identifier="de.mysterycode.wcf.htaccess.keeptempest.blog">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Rewrite application „::APP_NAME::“ (WCF 1.1) @ ::APP_DIR::
	RewriteCond %{QUERY_STRING} page=UserBlogOverview
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR:: [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserBlogEntry&entryID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?entry/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserBlog&userID=([0-9]+)&categoryID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?entry-list/&userID=%1 [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserBlogOverview&categoryID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?entry-list/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserBlog&userID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?entry-list/&userID=%1 [R=301,L]]]></content>

			<application>blog</application>
			<package>com.woltlab.blog</package>
			<path><![CDATA[]]></path>
		</content>
		<content identifier="de.mysterycode.wcf.htaccess.keeptempest.gallery">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Rewrite application „::APP_NAME::“ (WCF 1.1) @ ::APP_DIR::
	RewriteCond %{QUERY_STRING} page=UserGalleryOverview
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR:: [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserGalleryAlbumList&userID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?album/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserGalleryPhotos&userID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?user-image-ist/%1/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=UserGalleryPhoto&photoID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?image/%1/ [R=301,L]]]></content>

			<application>gallery</application>
			<package>com.woltlab.gallery</package>
			<path><![CDATA[]]></path>
		</content>
		<content identifier="de.mysterycode.wcf.htaccess.keeptempest.calendar">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Rewrite application „::APP_NAME::“ (WCF 1.1) @ ::APP_DIR::
	RewriteCond %{QUERY_STRING} page=CalendarMonth
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR:: [R=301,L]
	RewriteCond %{QUERY_STRING} page=CalendarWeek
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?weekly/ [R=301,L]
	RewriteCond %{QUERY_STRING} page=CalendarEvent&eventID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::APP_DIR::index.php?event/%1/ [R=301,L]]]></content>

			<application>calendar</application>
			<package>com.woltlab.calendar</package>
			<path><![CDATA[]]></path>
		</content>

		<content identifier="de.mysterycode.wcf.htaccess.keeptempest.wbb.seo">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Burning Board 3
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/([0-9]+)\-([^/\.]*)/last\-post\.html$ ::APP_DIR::index.php?thread/$4-$5/&action=lastPost [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/([0-9]+)\-([^/\.]*)/first\-new\-post\.html$ ::APP_DIR::index.php?thread/$4-$5/&action=firstNew [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/p([0-9]+)\-([^/\.]*)/?$ ::APP_DIR::index.php?thread/&postID=$4#post$4 [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/([0-9]+)\-([^/\.]*)/index([0-9]+)\.html$ ::APP_DIR::index.php?thread/$4-$5/&pageNo=$6 [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/([0-9]+)\-([^/\.]*)/?$ ::APP_DIR::index.php?thread/$4-$5/ [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/index([0-9]+)\.html$ ::APP_DIR::index.php?board/$2-$3/&pageNo=$4 [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::(board[0-9]+\-[^/\.]+/)*board([0-9]+)\-([^/\.]+)/?$ ::APP_DIR::index.php?board/$2/ [R=301,QSA,L]

	#TODO: wcf
	RewriteRule ^::OLD_APP_DIR::user/([0-9]+)\-([^/\.]*)/?$ ::WSC_DIR::/index.php/user/$1-$2/ [R=301,QSA,L]
	RewriteCond %{QUERY_STRING} page=Attachment&attachmentID=([0-9]+)
	RewriteRule ^::OLD_APP_DIR::index\.php$ ::WSC_DIR::/index.php?attachment/%1/ [R=301,QSA,L]]]></content>

			<application>wbb</application>
			<package>com.woltlab.wbb</package>
			<path><![CDATA[]]></path>
		</content>
		<content identifier="de.mysterycode.wcf.htaccess.keeptempest.blog.seo">
			<options><![CDATA[]]></options>
			<module><![CDATA[mod_rewrite.c]]></module>
			<content><![CDATA[	# Community Blog 1
	RewriteRule ^::OLD_APP_DIR::user/blog([0-9]+)\-([^/\.]*)/entry([0-9]+)\-([^/\.]*)/?$ ::APP_DIR::index.php?entry/$3-$4/ [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::user/blog([0-9]+)\-([^/\.]*)/category([0-9]+)\-([^/\.]*)/?$ ::APP_DIR::index.php?entry-list/&userID=$1 [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::blog/category([0-9]+)\-([^/\.]*)/?$ ::APP_DIR::index.php??entry-list/$1/ [R=301,QSA,L]
	RewriteRule ^::OLD_APP_DIR::user/blog([0-9]+)\-([^/\.]*)/?$ ::APP_DIR::index.php?entry-list/&userID=$1 [R=301,QSA,L]
	RewriteCond %{QUERY_STRING} page=UserBlogOverview
	RewriteRule ^::OLD_APP_DIR::index\.php$ /blog/ [R=301,QSA,L]]]></content>

			<application>blog</application>
